spring:
  profiles:
    active: dev
#thymeleaf配置
  thymeleaf:
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
#开发时关闭缓存,不然没法看到实时页面
    cache: false
mybatis:
  type-aliases-package: com.chenjx.redwars.domain
  mapper-locations: classpath:mapper/*.xml
